name: Update chinalist

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Get current time
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: "YYYY-MM-DD HH:mm"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up PyPy 3.9
        uses: actions/setup-python@v4
        with:
          python-version: pypy-3.9
          cache: pip
          cache-dependency-path: '**/requirements.txt'

      - name: Install dependencies
        run: pip install -r script/requirements.txt

      - name: Update
        run: |
          python script/main.py

      - name: Push
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: .
          git-config-name: github-actions[bot]
          git-config-email: 41898282+github-actions[bot]@users.noreply.github.com
          commit-message: updated ${{ steps.current-time.outputs.formattedTime }} UTC

      - name: Purge jsDelivr cache
        run: |
          wget -q -O - https://purge.jsdelivr.net/gh/Rongronggg9/chinalist@latest/chinalist_smart.txt
          wget -q -O - https://purge.jsdelivr.net/gh/Rongronggg9/chinalist@latest/chinalist_omega.txt
